config/routes.rb
Rails.application.routes.draw do
	root   'static_pages#home'
	get 'sessions/new'
	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
	resources :users
	resources :posts, :only => [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	validates :body, presence: true, length: { maximum: 500 }
	validates :title, presence: true, length: { maximum: 200 }
	validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	attr_accessor :remember_token
	before_save :downcase_email
	has_secure_password

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, presence: true, length: { maximum: 50 }
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: true
	has_secure_password
	validates :password, length: { minimum: 6}

	def downcase_email
		self.email = email.downcase
	end

	#generates a random token
	def self.new_token
		SecureRandom.urlsafe_base64
	end

	#takes a token and encrypts it for database
	def self.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
		BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end		

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def forget
		update_attribute(:remember_digest, nil)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :only_members, only: [:new, :create]

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		@post.author = current_user.name
		if @post.save
			flash[:success] = "Post saved"
			redirect_to posts_path
		else
			flash[:warning] = "Can't save post"
			render 'new'
		end
	end
	def index
		@posts = Post.order(id: :desc)
	end
	private
	def only_members
		unless logged_in?
			flash[:danger] = 'You must be a member and logged in to do that'
			redirect_to login_path
		end
	end
	def post_params
		params.require(:post).permit(:title, :body, :author)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
  		params[:session][:remember_me] == '1' ? remember(user) : forget(user)
  		redirect_to root_path
  	else
  		flash.now[:danger] = 'Invalid inputs'
  		render 'new'
  	end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		if(user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(:remember, cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end
	def logged_in?
		current_user
	end
	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end
	def remember(user)
		user.remember
		cookies.permanent[:remember_token] = user.remember_token
		cookies.permanent.signed[:user_id] = user.id
	end
	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="row navbar-fixed-bottom">
  <div class="col-md-12">
    <p class='footer-text'>
      A member-only secret place
    </p>
  </div>

</footer>

app/views/layouts/_head.html.erb
<head>
  <title>MembersOnlyClubhouse</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/_header.html.erb
<nav class='navbar navbar-default navbar-fixed-top navigation' %>
  <%= link_to "The House of secrets", root_path, class:'navbar-brand', id:'root' %>
  <ul class='nav nav-pills navbar-right'>
    <li><%= link_to "Members posts", posts_path,  id:'posts_link' %></li>
    <% if logged_in? %>
      <li><%= link_to "Members list", users_path, id:'members_link' %></li>
      <li><%= link_to "Profile", current_user, id:'profile_link' %></li>
      <li><%= link_to "Log out", logout_path, method: :delete, id:'logout_link' %></li>
    <% else %>
      <li><%= link_to "Log in", login_path, id:'login_link' %></li>
      <li><%= link_to "Sign in", new_user_path, id:'signin_link' %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid main">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 posts">
    <div id="index">
      <div class="create-new-post">
      <% if logged_in? %>
        <p class="btn btn-danger"><%= link_to "Create New Post", new_post_path, class:'newpostlink' %></p>
      <% end %>
      </div>
      <% @posts.each do |post| %>
        <div id="each-post">
            <p id="title"><%= post.title %></p>
          <p id="body"><%= post.body %></p>
          <p id="author">
            Author:
            <% if logged_in? %>
              <%= post.author %>
            <% else %>
              <%= link_to "You have to log in to know the author", login_path %>
            <% end %>
          </p>
        </div>
      <% end %>
    </div >

  </div>
</div>

app/views/posts/new.html.erb
<div class='row form' >
  <div class='col-md-6 col-md-offset-3' >

    <%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
    <div class="alert alert-danger">
      The form contains <%= pluralize(@post.errors.count, "error") %>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>

    <%= f.label :body %>
    <%= f.text_field :body, class: 'form-control' %>

    <%= f.submit 'Post', class:"btn btn-danger", id:'post_form' %>

    <% end %>

  </div>
</div>

app/views/static_pages/home.html.erb
<div class='row'>
  <div class='col-md-12'>

  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.label :email%>
<%= f.email_field :email, class: 'form-control' %>

<%= f.label :password%>
<%= f.password_field :password, class: 'form-control' %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation, class: 'form-control' %>

<%= f.submit 'Register', class:"btn btn-danger", id:'signin_form' %>

<% end %>

app/views/users/new.html.erb
<div class='row form' >
  <div class='col-md-6 col-md-offset-3' >
    <h1 id='signin_title'>Sign in</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1 id='profile'>MY INFORMATIONS</h1>
    <span><p id='name'>My name: <%= @user.name %></p></span>
  </div>
</div>